#!/usr/bin/env python3
"""Emit paper-ready LaTeX tables from the aggregate CSVs.

Reads the four `*_with_ci.csv` aggregates produced by
`compute_confidence_intervals.py` plus `judge_agreement.csv` and
`category_results.csv`, and writes one `.tex` file per table into
`paper/tables/`. Each `.tex` file is a standalone booktabs `tabular`
fragment intended to be `\\input{}`-ed from the paper sources.

Conventions:
  - ASR cells are rendered as `97.0 [89.6, 99.4]` — point estimate
    followed by a 95% Wilson CI. Phase A reviewers asked us never to
    omit uncertainty from headline numbers.
  - All `\\` escapes happen via raw string templates so the file is
    safe to drop into a LaTeX project unchanged.
  - Booktabs assumed (\\toprule, \\midrule, \\bottomrule).

Usage:
    python scripts/make_tables.py
    python scripts/make_tables.py --public_dir results/public --output_dir paper/tables
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from collections import defaultdict

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)


def _read_csv(path: str) -> list[dict]:
    if not os.path.exists(path):
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def _fmt_pct(x: float) -> str:
    return f"{100 * float(x):.1f}"


def _fmt_pct_ci(row: dict, key: str = "asr") -> str:
    pt = _fmt_pct(row[key])
    lo = _fmt_pct(row.get(f"{key}_ci_lo", row[key]))
    hi = _fmt_pct(row.get(f"{key}_ci_hi", row[key]))
    return f"{pt} \\,[{lo},\\,{hi}]"


def _fmt_num(x: str | float, prec: int = 2) -> str:
    try:
        return f"{float(x):.{prec}f}"
    except (TypeError, ValueError):
        return "---"


def _esc(s: str) -> str:
    """Minimal LaTeX escape for the strings we emit (model names, conditions)."""
    return (str(s)
            .replace("_", r"\_")
            .replace("&", r"\&")
            .replace("%", r"\%"))


# ── individual table emitters ───────────────────────────────────────────────

def emit_main_results(rows: list[dict], out_path: str) -> None:
    """Main results: dialect × target → ASR with 95% CI."""
    by_dialect: dict[str, dict[str, dict]] = defaultdict(dict)
    targets: list[str] = []
    for r in rows:
        by_dialect[r["dialect"]][r["target_model"]] = r
        if r["target_model"] not in targets:
            targets.append(r["target_model"])
    targets.sort()
    dialects = sorted(by_dialect.keys())

    lines = [
        r"% Auto-generated by scripts/make_tables.py — do not hand-edit.",
        r"\begin{tabular}{l" + "c" * len(targets) + "}",
        r"\toprule",
        "Dialect " + "".join(f" & {_esc(t)}" for t in targets) + r" \\",
        r"\midrule",
    ]
    for d in dialects:
        cells = []
        for t in targets:
            r = by_dialect[d].get(t)
            cells.append(_fmt_pct_ci(r) if r else "---")
        lines.append(_esc(d) + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_path, lines)


def emit_ablation_results(rows: list[dict], out_path: str) -> None:
    """Ablation: condition × dialect, faceted by target."""
    targets = sorted({r["target_model"] for r in rows})
    dialects = sorted({r["dialect"] for r in rows})
    conditions_order = [
        "english_original",
        "mandarin_translation",
        "naive_dialect_translation",
        "dialect_without_cultural_frame",
        "mandarin_with_cultural_frame",
        "full_dialect_cultural_frame",
    ]
    conditions = [c for c in conditions_order if any(r["ablation_condition"] == c for r in rows)]

    lines = [r"% Auto-generated by scripts/make_tables.py — do not hand-edit."]
    for target in targets:
        cell_lookup: dict[tuple, dict] = {
            (r["dialect"], r["ablation_condition"]): r
            for r in rows if r["target_model"] == target
        }
        lines += [
            r"% --- target: " + str(target),
            r"\begin{tabular}{l" + "c" * len(dialects) + "}",
            r"\toprule",
            f"Condition (target: {_esc(target)})" +
                "".join(f" & {_esc(d)}" for d in dialects) + r" \\",
            r"\midrule",
        ]
        for cond in conditions:
            cells = []
            for d in dialects:
                r = cell_lookup.get((d, cond))
                cells.append(_fmt_pct_ci(r) if r else "---")
            lines.append(_esc(cond) + " & " + " & ".join(cells) + r" \\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\par\medskip"]
    _write(out_path, lines)


def emit_model_generalization(rows: list[dict], out_path: str) -> None:
    """Cross-model: dialect × Phase-C target → ASR with CI."""
    emit_main_results(rows, out_path)


def emit_benchmark_generalization(rows: list[dict], out_path: str) -> None:
    """Cross-benchmark: benchmark × target × dialect → ASR with CI."""
    benchmarks = sorted({r["benchmark"] for r in rows})
    targets = sorted({r["target_model"] for r in rows})
    dialects = sorted({r["dialect"] for r in rows})

    lines = [
        r"% Auto-generated by scripts/make_tables.py — do not hand-edit.",
        r"\begin{tabular}{ll" + "c" * len(dialects) + "}",
        r"\toprule",
        "Benchmark & Target" + "".join(f" & {_esc(d)}" for d in dialects) + r" \\",
        r"\midrule",
    ]
    lookup: dict[tuple, dict] = {
        (r["benchmark"], r["target_model"], r["dialect"]): r for r in rows
    }
    for bench in benchmarks:
        for t in targets:
            cells = []
            for d in dialects:
                r = lookup.get((bench, t, d))
                cells.append(_fmt_pct_ci(r) if r else "---")
            lines.append(f"{_esc(bench)} & {_esc(t)} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_path, lines)


def emit_judge_agreement(rows: list[dict], out_path: str) -> None:
    """Inter-judge agreement matrix."""
    lines = [
        r"% Auto-generated by scripts/make_tables.py — do not hand-edit.",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Judge A & Judge B & N & Pearson & Spearman & Krippendorff $\alpha$ & Cohen $\kappa$ \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            f"{_esc(r['judge_a'])} & {_esc(r['judge_b'])} & {r['n']} & "
            f"{_fmt_num(r.get('pearson'), 3)} & {_fmt_num(r.get('spearman'), 3)} & "
            f"{_fmt_num(r.get('krippendorff_alpha'), 3)} & {_fmt_num(r.get('cohen_kappa'), 3)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_path, lines)


def emit_category_results(rows: list[dict], out_path: str) -> None:
    """Category × dialect ASR with CIs (single best target per row, for compactness)."""
    categories = sorted({r["category"] for r in rows})
    dialects = sorted({r["dialect"] for r in rows})
    targets = sorted({r["target_model"] for r in rows})

    lines = [r"% Auto-generated by scripts/make_tables.py — do not hand-edit."]
    for target in targets:
        lookup: dict[tuple, dict] = {
            (r["category"], r["dialect"]): r
            for r in rows
            if r["target_model"] == target and r["ablation_condition"] == "full_dialect_cultural_frame"
        }
        if not lookup:
            continue
        lines += [
            r"% --- target: " + str(target),
            r"\begin{tabular}{l" + "c" * len(dialects) + "}",
            r"\toprule",
            f"Category (target: {_esc(target)})" +
                "".join(f" & {_esc(d)}" for d in dialects) + r" \\",
            r"\midrule",
        ]
        for cat in categories:
            cells = []
            for d in dialects:
                r = lookup.get((cat, d))
                cells.append(_fmt_pct_ci(r) if r else "---")
            lines.append(_esc(cat) + " & " + " & ".join(cells) + r" \\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\par\medskip"]
    _write(out_path, lines)


def emit_query_efficiency(rows: list[dict], out_path: str) -> None:
    """Table 2: query-budget metrics for FOA conditions, faceted by target.

    Rows: FOA condition × dialect.  Columns: ASR@1, ASR@5, Avg.Q [CI], Med.Q, P90.Q.
    Non-FOA conditions are skipped (their query counts are trivially 1).
    """
    foa_rows = [r for r in rows if r.get("optimizer", "foa") == "foa"]
    targets = sorted({r["target_model"] for r in foa_rows})
    dialects = sorted({r["dialect"] for r in foa_rows})

    foa_conditions_order = [
        "full_dialect_cultural_frame",
        "dialect_without_cultural_frame",
        "mandarin_with_cultural_frame",
        "foa_generic_english",
        "foa_generic_mandarin",
        "foa_generic_chinese_register",
    ]
    present_conds = {r["ablation_condition"] for r in foa_rows}
    conditions = [c for c in foa_conditions_order if c in present_conds]

    lines = [r"% Auto-generated by scripts/make_tables.py — do not hand-edit."]
    for target in targets:
        lookup: dict[tuple, dict] = {
            (r["dialect"], r["ablation_condition"]): r
            for r in foa_rows if r["target_model"] == target
        }
        n_cols = len(dialects) * 5
        lines += [
            r"% --- target: " + str(target),
            r"\begin{tabular}{ll" + "r" * n_cols + "}",
            r"\toprule",
        ]
        # Dialect group header
        dialect_header = "Condition & Dialect"
        for d in dialects:
            dialect_header += f" & \\multicolumn{{5}}{{c}}{{{_esc(d)}}}"
        lines.append(dialect_header + r" \\")
        # Metric sub-header
        metric_header = " & "
        for _ in dialects:
            metric_header += r" & ASR@1 & ASR@5 & Avg.Q\,[CI] & Med.Q & P90.Q"
        lines.append(metric_header + r" \\")
        lines.append(r"\midrule")

        for cond in conditions:
            row_parts = [_esc(cond), ""]
            for d in dialects:
                r = lookup.get((d, cond))
                if r is None:
                    row_parts.extend(["---"] * 5)
                else:
                    asr1 = _fmt_pct(r.get("asr_at_1", 0))
                    asr5 = _fmt_pct(r.get("asr_at_5", 0))
                    avg_q = _fmt_num(r.get("avg_q", 0), 2)
                    q_lo = _fmt_num(r.get("avg_q_ci_lo", 0), 2)
                    q_hi = _fmt_num(r.get("avg_q_ci_hi", 0), 2)
                    med_q = _fmt_num(r.get("median_q", 0), 1)
                    p90_q = _fmt_num(r.get("p90_q", 0), 1)
                    row_parts.extend([asr1, asr5, f"{avg_q}\\,[{q_lo},\\,{q_hi}]", med_q, p90_q])
            lines.append(" & ".join(row_parts) + r" \\")

        lines += [r"\bottomrule", r"\end{tabular}", r"\par\medskip"]
    _write(out_path, lines)


def emit_hard_subset(rows: list[dict], out_path: str) -> None:
    """Table 3: full-set vs AdvBench-45-hard ASR per (dialect, target, condition).

    Rows: dialect × condition.  Columns per target: ASR-full [CI], ASR-hard [CI], ΔASR.
    """
    targets = sorted({r["target_model"] for r in rows})
    dialects = sorted({r["dialect"] for r in rows})
    conditions_order = [
        "full_dialect_cultural_frame",
        "dialect_without_cultural_frame",
        "mandarin_with_cultural_frame",
        "english_original",
        "mandarin_translation",
        "naive_dialect_translation",
    ]
    present_conds = {r["ablation_condition"] for r in rows}
    conditions = [c for c in conditions_order if c in present_conds]
    for c in sorted(present_conds):
        if c not in conditions:
            conditions.append(c)

    lines = [r"% Auto-generated by scripts/make_tables.py — do not hand-edit."]
    for dialect in dialects:
        lookup: dict[tuple, dict] = {
            (r["target_model"], r["ablation_condition"]): r
            for r in rows if r["dialect"] == dialect
        }
        n_cols = len(targets) * 3
        lines += [
            r"% --- dialect: " + str(dialect),
            r"\begin{tabular}{l" + "r" * n_cols + "}",
            r"\toprule",
        ]
        target_header = "Condition"
        for t in targets:
            target_header += f" & \\multicolumn{{3}}{{c}}{{{_esc(t)}}}"
        lines.append(target_header + r" \\")
        metric_header = ""
        for _ in targets:
            metric_header += r" & ASR-full [CI] & ASR-hard [CI] & $\Delta$ASR"
        lines.append(metric_header + r" \\")
        lines.append(r"\midrule")

        for cond in conditions:
            row_parts = [_esc(cond)]
            for t in targets:
                r = lookup.get((t, cond))
                if r is None:
                    row_parts.extend(["---", "---", "---"])
                else:
                    full_asr = float(r.get("asr_full", 0))
                    hard_asr = float(r.get("asr_hard", 0))
                    full_ci = (
                        f"{_fmt_pct(full_asr)}\\,"
                        f"[{_fmt_pct(r.get('asr_full_ci_lo', full_asr))},"
                        f"\\,{_fmt_pct(r.get('asr_full_ci_hi', full_asr))}]"
                    )
                    hard_ci = (
                        f"{_fmt_pct(hard_asr)}\\,"
                        f"[{_fmt_pct(r.get('asr_hard_ci_lo', hard_asr))},"
                        f"\\,{_fmt_pct(r.get('asr_hard_ci_hi', hard_asr))}]"
                    )
                    delta = f"{100 * (hard_asr - full_asr):+.1f}"
                    row_parts.extend([full_ci, hard_ci, delta])
            lines.append(" & ".join(row_parts) + r" \\")

        lines += [r"\bottomrule", r"\end{tabular}", r"\par\medskip"]
    _write(out_path, lines)


def emit_optimizer_comparison(rows: list[dict], out_path: str) -> None:
    """Table 4: optimizer × target → ASR [CI] + Avg.Q.

    Reads aggregate rows for all optimizer values. FOA is included for comparison.
    Rows: optimizer.  Columns: target → ASR [CI], Avg.Q.
    """
    targets = sorted({r["target_model"] for r in rows})
    optimizers_order = ["foa", "best_of_k", "greedy_coord", "random_one"]
    present_opts = {r.get("optimizer", "foa") for r in rows}
    optimizers = [o for o in optimizers_order if o in present_opts]
    for o in sorted(present_opts):
        if o not in optimizers:
            optimizers.append(o)

    # One row per optimizer, columns per target: ASR [CI] + Avg.Q [CI]
    lookup: dict[tuple, dict] = {
        (r.get("optimizer", "foa"), r["target_model"]): r for r in rows
    }
    n_cols = len(targets) * 2
    lines = [
        r"% Auto-generated by scripts/make_tables.py — do not hand-edit.",
        r"\begin{tabular}{l" + "rr" * len(targets) + "}",
        r"\toprule",
    ]
    target_header = "Optimizer"
    for t in targets:
        target_header += f" & \\multicolumn{{2}}{{c}}{{{_esc(t)}}}"
    lines.append(target_header + r" \\")
    metric_header = ""
    for _ in targets:
        metric_header += r" & ASR [CI] & Avg.Q [CI]"
    lines.append(metric_header + r" \\")
    lines.append(r"\midrule")

    for opt in optimizers:
        row_parts = [_esc(opt)]
        for t in targets:
            r = lookup.get((opt, t))
            if r is None:
                row_parts.extend(["---", "---"])
            else:
                asr_cell = _fmt_pct_ci(r)
                avg_q = _fmt_num(r.get("avg_queries", r.get("avg_q", 0)), 2)
                q_lo = _fmt_num(r.get("avg_queries_ci_lo", r.get("avg_q_ci_lo", 0)), 2)
                q_hi = _fmt_num(r.get("avg_queries_ci_hi", r.get("avg_q_ci_hi", 0)), 2)
                q_cell = f"{avg_q}\\,[{q_lo},\\,{q_hi}]"
                row_parts.extend([asr_cell, q_cell])
        lines.append(" & ".join(row_parts) + r" \\")

    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_path, lines)


def emit_full_matrix(rows: list[dict], out_path: str) -> None:
    """Appendix: all (condition × dialect) cells per target → ASR [CI] + Avg.Q.

    Reads ablation_results_with_ci.csv (foa rows only).
    """
    targets = sorted({r["target_model"] for r in rows})
    dialects = sorted({r["dialect"] for r in rows})
    conditions_order = [
        "english_original",
        "mandarin_translation",
        "naive_dialect_translation",
        "dialect_without_cultural_frame",
        "mandarin_with_cultural_frame",
        "full_dialect_cultural_frame",
        "foa_generic_english",
        "foa_generic_mandarin",
        "foa_generic_chinese_register",
    ]
    present_conds = {r["ablation_condition"] for r in rows}
    conditions = [c for c in conditions_order if c in present_conds]
    for c in sorted(present_conds):
        if c not in conditions:
            conditions.append(c)

    lines = [r"% Auto-generated by scripts/make_tables.py — do not hand-edit."]
    for target in targets:
        lookup: dict[tuple, dict] = {
            (r["dialect"], r["ablation_condition"]): r
            for r in rows if r["target_model"] == target
        }
        n_cols = len(dialects) * 2
        lines += [
            r"% --- target: " + str(target),
            r"\begin{tabular}{l" + "rr" * len(dialects) + "}",
            r"\toprule",
        ]
        dialect_header = "Condition"
        for d in dialects:
            dialect_header += f" & \\multicolumn{{2}}{{c}}{{{_esc(d)}}}"
        lines.append(dialect_header + r" \\")
        metric_header = ""
        for _ in dialects:
            metric_header += r" & ASR [CI] & Avg.Q"
        lines.append(metric_header + r" \\")
        lines.append(r"\midrule")

        for cond in conditions:
            row_parts = [_esc(cond)]
            for d in dialects:
                r = lookup.get((d, cond))
                if r is None:
                    row_parts.extend(["---", "---"])
                else:
                    asr_cell = _fmt_pct_ci(r)
                    avg_q = _fmt_num(r.get("avg_queries", 0), 2)
                    row_parts.extend([asr_cell, avg_q])
            lines.append(" & ".join(row_parts) + r" \\")

        lines += [r"\bottomrule", r"\end{tabular}", r"\par\medskip"]
    _write(out_path, lines)


def _write(path: str, lines: list[str]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path}")


def main() -> int:
    p = argparse.ArgumentParser(description="Emit paper LaTeX tables from aggregate CSVs.")
    p.add_argument("--public_dir", default=os.path.join(_ROOT, "results", "public"))
    p.add_argument("--output_dir", default=os.path.join(_ROOT, "paper", "tables"))
    args = p.parse_args()

    targets = [
        ("main_results_with_ci.csv", "main_results.tex", emit_main_results),
        ("ablation_results_with_ci.csv", "ablation_results.tex", emit_ablation_results),
        ("model_generalization_with_ci.csv", "model_generalization.tex", emit_model_generalization),
        ("benchmark_generalization_with_ci.csv", "benchmark_generalization.tex", emit_benchmark_generalization),
        ("judge_agreement.csv", "judge_agreement.tex", emit_judge_agreement),
        ("category_results.csv", "category_results.tex", emit_category_results),
        ("query_budget_analysis.csv", "query_efficiency.tex", emit_query_efficiency),
        ("hard_subset_analysis.csv", "hard_subset.tex", emit_hard_subset),
        ("optimizer_baselines.csv", "optimizer_comparison.tex", emit_optimizer_comparison),
        ("ablation_results_with_ci.csv", "full_matrix.tex", emit_full_matrix),
    ]
    n_written = 0
    for src, dst, emit_fn in targets:
        src_path = os.path.join(args.public_dir, src)
        rows = _read_csv(src_path)
        if not rows:
            print(f"[skip] {src} (missing or empty)")
            continue
        emit_fn(rows, os.path.join(args.output_dir, dst))
        n_written += 1
    if n_written == 0:
        print("No tables emitted. Run aggregate_results.py and "
              "compute_confidence_intervals.py first.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
